(()=>{const data=window.FOTODISOGNO;if(!data)return;const body=document.body,projectId=body.dataset.project,project=data.projects.find(i=>i.id===projectId);if(!project)return;const state={lang:"nl",index:0,touchStartX:0,touchStartY:0,uiTimer:0,zoomed:false},$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],imagePath=f=>`../../images/${f.split("/").map(encodeURIComponent).join("/")}`,t=k=>data.translations[state.lang]?.[k]||data.translations.en[k]||k,localized=v=>v?.[state.lang]||v?.en||"";
function setMeta(){const title=localized(project.title),description=localized(project.description);document.title=`${title} — FotodiSogno`;$('meta[name="description"]')?.setAttribute("content",description);$('meta[property="og:title"]')?.setAttribute("content",`${title} — FotodiSogno`);$('meta[property="og:description"]')?.setAttribute("content",description);$('meta[property="og:image"]')?.setAttribute("content",`https://fotodisogno.com/images/${encodeURIComponent(project.cover)}`);$('link[rel="canonical"]')?.setAttribute("href",`https://fotodisogno.com/projects/${project.id}/`)}
function applyLanguage(){document.documentElement.lang=state.lang;$$('[data-i18n]').forEach(n=>{const v=t(n.dataset.i18n);if(v)n.textContent=v});$$('[data-lang]').forEach(b=>{b.classList.toggle('active',b.dataset.lang===state.lang);b.setAttribute('aria-pressed',String(b.dataset.lang===state.lang))});$('#projectTitle').textContent=localized(project.title);$('#projectDescription').textContent=localized(project.description);$('#projectLocation').textContent=localized(project.location);$('#lightboxProjectTitle').textContent=localized(project.title);const home=`../../?lang=${state.lang}#work`;$('#backHome').href=home;$('#brandHome').href=home;const index=data.projects.findIndex(i=>i.id===project.id),previous=data.projects[(index-1+data.projects.length)%data.projects.length],next=data.projects[(index+1)%data.projects.length],previousLink=$('#previousProject'),nextLink=$('#nextProject');previousLink.href=`../${previous.id}/?lang=${state.lang}`;nextLink.href=`../${next.id}/?lang=${state.lang}`;previousLink.querySelector('strong').textContent=localized(previous.title);nextLink.querySelector('strong').textContent=localized(next.title);const url=new URL(location.href);url.searchParams.set('lang',state.lang);history.replaceState(null,'',`${url.pathname}${url.search}${url.hash}`);setMeta()}
function renderStory(){const story=$('#story');story.innerHTML='';project.photos.forEach((photo,index)=>{const frame=document.createElement('article');frame.className=`story-frame story-frame--${photo.layout||'full'} reveal`;const button=document.createElement('button');button.className='story-button';button.type='button';button.dataset.photoIndex=String(index);button.dataset.cursor='view';button.setAttribute('aria-label',`${t('viewImage')} ${index+1}`);button.innerHTML=`<img class="image-fade" src="${imagePath(photo.src)}" alt="${photo.alt}" loading="${index<2?'eager':'lazy'}" decoding="async" sizes="(max-width:760px) 100vw,90vw"><span class="story-index">${String(index+1).padStart(2,'0')} / ${String(project.photos.length).padStart(2,'0')}</span>`;frame.appendChild(button);story.appendChild(frame)});prepareImages(story);observeReveals();bindCursorTargets(story)}
function prepareImages(root=document){$$('img.image-fade',root).forEach(image=>{if(image.complete)image.classList.add('is-loaded');else image.addEventListener('load',()=>image.classList.add('is-loaded'),{once:true})})}
let revealObserver;function observeReveals(){const items=$$('.reveal:not(.reveal-observed)');if(matchMedia('(prefers-reduced-motion:reduce)').matches||!('IntersectionObserver'in window)){items.forEach(i=>i.classList.add('visible'));return}if(!revealObserver)revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{rootMargin:'0px 0px -7% 0px',threshold:.06});items.forEach(item=>{item.classList.add('reveal-observed');revealObserver.observe(item)})}
function preloadAround(index){[-1,1].forEach(offset=>{const photo=project.photos[(index+offset+project.photos.length)%project.photos.length],image=new Image;image.src=imagePath(photo.src)})}
function updateLightboxPhoto(animate=true){const image=$('#lightboxImage'),photo=project.photos[state.index];if(animate)image.classList.add('is-changing');state.zoomed=false;image.classList.remove('is-zoomed');const nextImage=new Image;nextImage.onload=()=>{image.src=nextImage.src;image.alt=photo.alt;requestAnimationFrame(()=>image.classList.remove('is-changing'))};nextImage.src=imagePath(photo.src);$('#lightboxCounter').textContent=`${String(state.index+1).padStart(2,'0')} / ${String(project.photos.length).padStart(2,'0')}`;$('#lightboxProgressBar').style.width=`${(state.index+1)/project.photos.length*100}%`;preloadAround(state.index)}
function showLightboxUI(){const lightbox=$('#projectLightbox');lightbox.classList.remove('ui-hidden');clearTimeout(state.uiTimer);state.uiTimer=setTimeout(()=>lightbox.classList.add('ui-hidden'),2200)}
function openLightbox(index){state.index=index;updateLightboxPhoto(false);const lightbox=$('#projectLightbox');lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');body.classList.add('overlay-open');showLightboxUI();requestAnimationFrame(()=>$('#closeLightbox').focus({preventScroll:true}))}
function closeLightbox(){const lightbox=$('#projectLightbox');lightbox.classList.remove('open','ui-hidden');lightbox.setAttribute('aria-hidden','true');body.classList.remove('overlay-open');$('#lightboxImage').src='';clearTimeout(state.uiTimer)}
function moveLightbox(direction){state.index=(state.index+direction+project.photos.length)%project.photos.length;updateLightboxPhoto();showLightboxUI()}
function toggleZoom(){state.zoomed=!state.zoomed;$('#lightboxImage').classList.toggle('is-zoomed',state.zoomed);showLightboxUI()}
function handlePointerDown(event){state.touchStartX=event.clientX;state.touchStartY=event.clientY}function handlePointerUp(event){const dx=event.clientX-state.touchStartX,dy=event.clientY-state.touchStartY;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.25)moveLightbox(dx<0?1:-1)}
function setupHeroTransition(){const hero=$('#projectHeroImage'),stored=sessionStorage.getItem('fotodisogno-transition-project');if(stored===project.id){hero.style.viewTransitionName=`project-${project.id}`;setTimeout(()=>{hero.style.viewTransitionName='';sessionStorage.removeItem('fotodisogno-transition-project')},1500)}}
function setupHero(){const hero=$('#projectHeroImage');hero.src=imagePath(project.cover);hero.alt=localized(project.title);hero.style.objectPosition=project.position||'center';body.dataset.theme=project.theme||'warm';prepareImages();setupHeroTransition();if(!matchMedia('(prefers-reduced-motion:reduce)').matches){let ticking=false;addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(()=>{hero.style.transform=`translate3d(0,${Math.min(scrollY*.04,36)}px,0) scale(1.04)`;ticking=false});ticking=true}},{passive:true})}}
const cursor=$('#cursor'),cursorLabel=$('#cursorLabel');let cursorFrame=0,cursorX=0,cursorY=0;function moveCursor(event){cursorX=event.clientX;cursorY=event.clientY;if(!cursorFrame)cursorFrame=requestAnimationFrame(()=>{if(cursor)cursor.style.transform=`translate(${cursorX}px,${cursorY}px) translate(-50%,-50%) scale(${cursor.classList.contains('active')?1:.5})`;cursorFrame=0})}
function bindCursorTargets(root=document){if(!cursor||!matchMedia('(hover:hover) and (pointer:fine)').matches)return;$$('[data-cursor]',root).forEach(target=>{if(target.dataset.cursorBound==='true')return;target.dataset.cursorBound='true';target.addEventListener('mouseenter',()=>{cursorLabel.textContent='View';cursor.classList.add('active')});target.addEventListener('mouseleave',()=>cursor.classList.remove('active'))})}
function init(){const requested=new URL(location.href).searchParams.get('lang');state.lang=data.translations[requested]?requested:'nl';$('#projectYear').textContent=project.year;$('#year').textContent=new Date().getFullYear();setupHero();applyLanguage();renderStory();$$('.project-intro,.project-navigation,.project-contact').forEach(node=>node.classList.add('reveal'));observeReveals();bindCursorTargets();$$('[data-lang]').forEach(button=>button.addEventListener('click',()=>{state.lang=button.dataset.lang;applyLanguage()}));$('#story').addEventListener('click',event=>{const button=event.target.closest('[data-photo-index]');if(button)openLightbox(Number(button.dataset.photoIndex))});$('#closeLightbox').addEventListener('click',closeLightbox);$('#zoomLightbox').addEventListener('click',toggleZoom);$('#lightboxImage').addEventListener('dblclick',toggleZoom);$('#previousPhoto').addEventListener('click',()=>moveLightbox(-1));$('#nextPhoto').addEventListener('click',()=>moveLightbox(1));const stage=$('#lightboxStage');stage.addEventListener('pointerdown',handlePointerDown);stage.addEventListener('pointerup',handlePointerUp);stage.addEventListener('pointermove',showLightboxUI,{passive:true});$('#projectLightbox').addEventListener('click',event=>{showLightboxUI();if(event.target===$('#projectLightbox'))closeLightbox()});addEventListener('mousemove',moveCursor,{passive:true});addEventListener('scroll',()=>$('#projectHeader').classList.toggle('scrolled',scrollY>18),{passive:true});addEventListener('load',()=>setTimeout(()=>body.classList.add('is-ready'),420),{once:true});if(document.readyState==='complete')setTimeout(()=>body.classList.add('is-ready'),420);document.addEventListener('keydown',event=>{if(!$('#projectLightbox').classList.contains('open'))return;if(event.key==='Escape')closeLightbox();if(event.key==='ArrowLeft')moveLightbox(-1);if(event.key==='ArrowRight')moveLightbox(1);if(event.key.toLowerCase()==='z')toggleZoom()})}
document.addEventListener('DOMContentLoaded',init)})();
