(()=>{const data=window.FOTODISOGNO,body=document.body,project=data?.projects.find(item=>item.id===body.dataset.project);if(!project)return;const title=project.title.en,description=project.description.en,cover=`../../images/${encodeURIComponent(project.cover)}`;document.body.insertAdjacentHTML('afterbegin',`
<a class="skip-link" href="#projectMain">Skip to content</a>
<div class="page-intro" aria-hidden="true"><span>FotodiSogno</span></div>
<div class="cursor" id="cursor" aria-hidden="true"><span id="cursorLabel">View</span></div>
<header class="project-header" id="projectHeader">
  <a class="project-back" id="backHome" href="../../#work"><span aria-hidden="true">←</span><span data-i18n="backHome">Back to portfolio</span></a>
  <a class="brand" id="brandHome" href="../../" aria-label="FotodiSogno — home"><span class="brand-name">FotodiSogno</span></a>
  <div class="language-switcher" aria-label="Language"><button type="button" data-lang="nl">NL</button><button type="button" data-lang="en">EN</button><button type="button" data-lang="pl">PL</button></div>
</header>
<main id="projectMain">
  <section class="project-hero" aria-labelledby="projectTitle"><img class="image-fade" id="projectHeroImage" src="${cover}" alt="${title}" fetchpriority="high" decoding="async"><div class="project-hero-shade" aria-hidden="true"></div><div class="project-hero-copy"><p class="project-kicker" data-i18n="projectLabel">Photography series</p><h1 id="projectTitle">${title}</h1><div class="project-meta"><span id="projectLocation">${project.location.en}</span><span id="projectYear">${project.year}</span></div></div></section>
  <section class="project-intro"><p class="project-intro-index">01 — ${String(project.photos.length).padStart(2,'0')}</p><p class="project-intro-copy" id="projectDescription">${description}</p></section>
  <section class="story" id="story" aria-label="${title} photography"></section>
  <nav class="project-navigation" aria-label="Project navigation"><a class="project-nav-link" id="previousProject" href="#"><small data-i18n="previousProject">Previous project</small><strong></strong></a><a class="project-nav-link" id="nextProject" href="#"><small data-i18n="nextProject">Next project</small><strong></strong></a></nav>
  <section class="project-contact"><div class="project-contact-inner"><h2 data-i18n="projectContact">Have a project in mind?</h2><a href="mailto:fotodisogno@gmail.com"><span data-i18n="projectContactCta">Get in touch</span><span aria-hidden="true">↗</span></a></div></section>
</main>
<footer class="site-footer"><div><span class="footer-brand">FotodiSogno</span><span>© <span id="year"></span> Rafał Wilk</span></div><p data-i18n="copyright">All photographs and content are protected by copyright and may not be used without written permission.</p></footer>
<div class="project-lightbox" id="projectLightbox" aria-hidden="true"><div class="lightbox-top lightbox-ui"><span class="lightbox-title" id="lightboxProjectTitle">${title}</span><div class="lightbox-tools"><button class="lightbox-tool" id="zoomLightbox" type="button" aria-label="Zoom" title="Zoom">＋</button><button class="lightbox-tool" id="closeLightbox" type="button" aria-label="Close" title="Close">×</button></div></div><div class="lightbox-stage" id="lightboxStage"><button class="lightbox-arrow lightbox-prev lightbox-ui" id="previousPhoto" type="button" aria-label="Previous photo">‹</button><div class="lightbox-image-wrap"><img class="lightbox-image" id="lightboxImage" src="" alt=""></div><button class="lightbox-arrow lightbox-next lightbox-ui" id="nextPhoto" type="button" aria-label="Next photo">›</button></div><div class="lightbox-bottom lightbox-ui"><span class="lightbox-counter" id="lightboxCounter">01 / 01</span><span class="lightbox-progress" aria-hidden="true"><span id="lightboxProgressBar"></span></span></div></div>`);})();
